### ISSUE TITLE
[Bug] Houdini-preprocess errors on postcss-syntax

### ISSUE THREAD

**Issue by benbender** [AlecAivazis/houdini#159]
If I'm installing houdini along with postcss and f.e. postcss-nesting, houdini-preprocess errors on "invalid css" as postcss doesn't seem to be running beforehand. If I remove houdini from the preprocess-chain, everything works as intended.

````
> svelte-check


====================================
Loading svelte-check in workspace: /Users/bb/Work/houdini-postcss
Getting Svelte diagnostics...

Preprocessing failed
CompileError [ParseError]: Identifier is expected
    at error (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:15797:19)
    at Parser$1$1.error (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:15873:9)
    at Object.read_style [as read] (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:12262:20)
    at tag (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:14932:33)
    at new Parser$1$1 (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:15832:21)
    at parse$3 (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:15964:20)
    at file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:31346:30
    at step (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:66:23)
    at Object.next (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:47:53)
    at fulfilled (file:///Users/bb/Work/houdini-postcss/node_modules/.pnpm/houdini-common@0.10.1_graphql@15.5.0/node_modules/houdini-common/build/esm/index.js:37:58) {
  code: 'css-syntax-error',
  start: { line: 6, column: 9, character: 162 },
  end: { line: 6, column: 9, character: 162 },
  pos: 162,
  filename: undefined,
  frame: '4: <style lang="postcss">\n' +
    '5:     p {\n' +
    '6:         & a {\n' +
    '            ^\n' +
    '7:             color: lime;\n' +
    '8:         }'
}
/Users/bb/Work/houdini-postcss/src/routes/index.svelte:1:1
Warn: Identifier is expected (svelte)
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
````

The same error occurs when running the dev-server.

Minimal Repro: https://github.com/benbender/houdini-postcss-repro

**Comment by pixelmund** [comment]
Did you try moving houdinis preprocessor before svelte-preprocess?

**Comment by pixelmund** [comment]
Im using postcss together with Houdini and it's working fine but it might be because im only using tailwind

**Comment by benbender** [comment]
Yed, no change... Seems to be a recent issue, as I also didn't notice any problems before. The repro is done simply by installing via create-svelte@next and adding the packages. So I don't see any option do screw it up on my side.

**Comment by benbender** [comment]
Update: The offending change is the update from svelte 3.34 to 3.39 in this PR on sveltejs/kit#2182. If I pin svelte to 3.34, the error disappears.

**Comment by ledesmablt** [comment]
Postcss related error when I run `houdini generate`. I'm also using tailwind.
```
Error: Encountered error parsing src/routes/manage/product/[productId].svelte: Semicolon or block is expected
    at file:///Users/benj/projects/app/node_modules/houdini/build/cmd.js:77579:52
    at step (file:///Users/benj/projects/app/node_modules/houdini/build/cmd.js:124:23)
    at Object.throw (file:///Users/benj/projects/app/node_modules/houdini/build/cmd.js:105:53)
    at rejected (file:///Users/benj/projects/app/node_modules/houdini/build/cmd.js:96:65)
```

Here's my `svelte.config.js` file.

```
import preprocess from 'svelte-preprocess'
import node from '@sveltejs/adapter-node'
import houdini from 'houdini-preprocess'
import path from 'path'

const config = {
  preprocess: [preprocess({ postcss: true }), houdini()],

  kit: {
    target: '#svelte',
    adapter: node(),
    vite: {
      resolve: {
        alias: {
          $houdini: path.resolve('.', '$houdini')
        }
      }
    }
  }
}

export default config
```

**Comment by AlecAivazis** [comment]
Hey yall! Sorry you're running into this. I'll try to get a fix out for this over the weekend if someone doesn't get to it first. [Here](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-common/src/parse.ts) is where the parse file is defined. Since houdini doesn't really care about the actual contents of the style block, I suspect the best way to approach this is to do a similar preprocessing that strips the actual content away before running the parser.

**Comment by AlecAivazis** [comment]
This should be fixed in version `0.10.5`. If someone could confirm, that would be awesome!

**Comment by ledesmablt** [comment]
works fine now, thanks!!

**Comment by benbender** [comment]
+1. Thanks for the quick fix!
