### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by SorenHolstHansen** [AlecAivazis/houdini#182]
I have mocked a really simple cursor based pagination query
```js
@ObjectType()
class MockPaginatedStuff {
	@Field(() => Number)
	id: number;

	@Field(() => Number)
	rank: number;
}

const array: MockPaginatedStuff[] = [
	{ id: 7, rank: 11001 },
	{ id: 6, rank: 200 },
	{ id: 3, rank: 120 },
	{ id: 1, rank: 100 },
	{ id: 2, rank: 90 },
	{ id: 4, rank: 60 },
	{ id: 5, rank: 44 },
	{ id: 8, rank: 1 }
];

@Resolver(Sudoku)
export class SudokuResolver {
	@Query(() => [MockPaginatedStuff])
	mockPagination(
		@Arg('first') first: number,
		@Arg('cursor', { nullable: true }) cursor?: number
	): MockPaginatedStuff[] {
		return array.filter((a) => (cursor ? a.rank < cursor : true)).slice(0, first);
	}
}
```
However when I try and paginate it in svelte
```js
const { data } = paginatedQuery(graphql`
		query MockPagination {
			mockPagination(first: 5, cursor: null) @paginate {
				id
				rank
			}
		}
	`);
```
I get 
```js
TypeError: Cannot read property 'type' of undefined
    at _loop_1 (file:///Users/.../node_modules/houdini/build/cmd.js:77057:75)
    at selection (file:///Users/.../node_modules/houdini/build/cmd.js:77135:13)
    at _loop_1 (file:///Users/.../node_modules/houdini/build/cmd.js:77106:35)
    at selection (file:///Users/.../node_modules/houdini/build/cmd.js:77135:13)
    at file:///Users/.../node_modules/houdini/build/cmd.js:77618:56
    at step (file:///Users/.../node_modules/houdini/build/cmd.js:124:23)
    at Object.next (file:///.../node_modules/houdini/build/cmd.js:105:53)
    at file:///Users/...node_modules/houdini/build/cmd.js:98:71
    at new Promise (<anonymous>)
    at __awaiter$1 (file:///Users/.../node_modules/houdini/build/cmd.js:94:12
```
What am I doing wrong?

**Comment by AlecAivazis** [comment]
Hey @SorenHolstHansen - I think this error is because of a problem in your schema. In order for a field to implement cursor-based pagination it has to conform to the [connection spec](https://relay.dev/graphql/connections.htm). I see two errors in the query you shared: 

- the argument passed to the field to denote which entry is at the end of a page should be `after` or `before` (you have `cursor`). It's also probably worth mentioning that you don't need to pass `after` to your field. Houdini will take care of that for you when you call `loadNextPage`.
- the return type needs to follow the Connection interface. From your example, it looks like your field just returns a list

Fixing both of these these turns your query would look something like:

```javascript
const { data } = paginatedQuery(graphql`
    query MockPagination {
        mockPagination(first: 5) @paginate {
            edges { 
                node { 
                    id
                    rank
                }
            }
        }
    }
`);
```

**Comment by SorenHolstHansen** [comment]
Oh, thanks! Didn't know about that stuff
