### ISSUE TITLE
Problem with fragments

### ISSUE THREAD

**Issue by neoel** [AlecAivazis/houdini#190]
I probably have done something wrong, but I can't see what. 

The error I'm seeing is:
```
find frag Likes_3K7mRP Likes
Error: Fragment doesn't exist in its own document?!
    at file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:77683:55
    at step (file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:124:23)
    at Object.next (file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:105:53)
    at file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:98:71
    at new Promise (<anonymous>)
    at __awaiter$1 (file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:94:12)
    at file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:77627:58
    at Array.map (<anonymous>)
    at file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:77627:30
    at step (file:///home/dexter/Projects/BENDERFACToRY/vault/node_modules/houdini/build/cmd.js:124:23)
```

I added the 'find frag' log statement to figure out what's in there:
```
    matchingFragment = fragments.find(function (fragment) { 
      console.log('find frag', fragment.name.value, name)
      return fragment.name.value === name; });
    if (!matchingFragment) {
        throw new Error("Fragment doesn't exist in its own document?!");
    }
```

The setup for my fragment is:
```ts
	import { fragment, mutation, graphql, Likes } from '$houdini';

	export let id;
	export let likes: Likes;

	const data = fragment(
		graphql`
			fragment Likes on media @arguments(userId: { type: "uuid!" }) {
				likes(where: { user_id: { _eq: $userId } }) {
					media_id
				}
			}
		`,
		likes
	);
```

And the 'parent' is:
```ts
const { data, loading, error } = query<AllTracks>(graphql`
		query AllTracks($userId: uuid!) {
			media(order_by: [{ likes_aggregate: { count: desc } }, { title: asc }]) {
				title
				bpm
				data_folder
				id
				recorded_date
				stereo_mix
				tracks
				likes_aggregate {
					aggregate {
						count
					}
				}
				...Likes @with(userId: $userId)
			}
		}
	`);
```

**Comment by AlecAivazis** [comment]
Ah damn! I have a hunch what's causing this, I'll try to get something out ASAP. Thanks for reporting it

**Comment by AlecAivazis** [comment]
Turns out I was wrong about what the problem was. I'm still trying to hunt this down, it seems to work in the example app. I'll try to dig a little deeper some time over the weekend. If you can spot the difference between what you have and the example in the [missing-fragment-definition branch](https://github.com/AlecAivazis/houdini/tree/missing-fragment-definition/example/src) that would be super helpful.  [Here's](https://github.com/AlecAivazis/houdini/blob/missing-fragment-definition/example/src/routes/%5Bfilter%5D.svelte#L34) the parent. And [here](https://github.com/AlecAivazis/houdini/blob/missing-fragment-definition/example/src/lib/ItemEntry.svelte#L17) is the child

**Comment by neoel** [comment]
It looks the same to me. the only thing different is the query structure

**Comment by AlecAivazis** [comment]
Going to close this since its gone stale. If you have a reproducible error I'd love to take a closer look
