### ISSUE TITLE
Tips for debugging failed fetches?

### ISSUE THREAD

**Issue by thormuller** [AlecAivazis/houdini#72]
I have not yet had success with fetch queries to my remote graphql server (Hasura). I'm getting a `Cannot read property 'data' of undefined` error, and after adding logging to the environment.js my best guess is that it's not even attempting to fetch since the logging isn't appearing. I'm not clear on the best way to debug this issue, and am hoping a solution here will help others.

My query is adapted straight from the documentation:
```
	import { query, graphql, AllUsers } from '$houdini';
	const { data } = query<AllUsers>(graphql`
		query AllUsers {
			kl_users {
				email
				uid
			}
		}
	`);
```

and the error is:
```
Cannot read property 'data' of undefined
TypeError: Cannot read property 'data' of undefined
    at Module.query (/$houdini/runtime/query.js:15:48)
    at Login.svelte:33:29
    at Object.$$render (<PATH>/node_modules/svelte/internal/index.js:1380:22)
    at eval (/src/lib/layout/Header.svelte:15:115)
    at Object.$$render (<PATH>/node_modules/svelte/internal/index.js:1380:22)
    at eval (<PATH>/src/routes/$layout.svelte:42:94)
    at Object.$$render (<PATH>/node_modules/svelte/internal/index.js:1380:22)
    at root.svelte:31:44
    at $$render (<PATH>/node_modules/svelte/internal/index.js:1380:22)
    at Object.render (<PATH>/node_modules/svelte/internal/index.js:1388:26)
```

**Comment by AlecAivazis** [comment]
Hey @thormuller! 

It might help to understand what the generated load function looks like so you can add logs in the right spot to capture the information you are investigating. At the moment, the most reliable place to see this is one of the [snapshot tests](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-preprocess/src/transforms/query.test.ts#L9). The [top snapshot](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-preprocess/src/transforms/query.test.ts#L23-L57) is what is generated for the `load` function and the [second snapshot](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini-preprocess/src/transforms/query.test.ts#L58-L78) is what's left behind of your component. If you want to just test that `load` is being called where/when you think it is, you can add a `console.log` in the [constructor for RequestContext](https://github.com/AlecAivazis/houdini/blob/main/packages/houdini/runtime/network.ts#L139). You find a very similar file to the one in that link inside of `$houdini/runtime/network.js`.


It's probably worth mentioning, for anyone who finds this issue that the first request your application fires will get logged on your server, not in the browser console. Queries that fire after the first request will be sent from your browser and logged in the browser's console.

**Comment by thormuller** [comment]
Brilliant, thanks for the tips. I'll give that a go.

**Comment by thormuller** [comment]
The issue is with line 15 in query.js: 

`const initialValue = document.initialValue.data;`

There is no initialValue on document which leads to the aforementioned error. Does that imply that something is off in the configuration somewhere? The document object in query.js looks like this:
```
{
  initialValue: undefined,
  variables: undefined,
  kind: 'HoudiniQuery',
  artifact: {
    name: 'AllUsers',
    kind: 'HoudiniQuery',
    hash: '3509969641628a2b17ad4cbc3c28a55b',
    raw: 'query AllUsers {\n  kl_users {\n    email\n    uid\n  }\n}\n',
    rootType: 'query_root',
    selection: { kl_users: [Object] }
  }
}
```

**Comment by AlecAivazis** [comment]
Hm, well getting that far means the `load` function didn't see an error in the response. It also means that the `data` field in the response is `undefined` Having a query with no value and no errors seems like something is going on with the requests to the server.

 Are you seeing `load` invoked when you navigate to a route? 

Regardless, we clearly need a better error message if `query` is invoked with an `undefined` initial value.

**Comment by thormuller** [comment]
I'm not seeing the log message when I load the route with the query. I'd think the load would happen before the query was fired, but I see no evidence of it. The log is in network.js like so:
```
export class RequestContext {
    constructor(ctx) {
        console.log("network.js")
        this.continue = true;
        this.returnValue = {};
        this.context = ctx;
    }
```

**Comment by AlecAivazis** [comment]
Do you see anything if you add a log on the api side of resolving `kl_users`? 

Is this the same repo you shared earlier? If so, mind pushing it up so I can take a closer look? I dont need access to a working API in order to see your problem so no need to worry about making that available

**Comment by thormuller** [comment]
Thanks! Just pushed the latest up to that repo. I hope this proves useful for general purposes!

**Comment by thormuller** [comment]
FYI, logging confirms the graphql api is not receiving any requests, while it is receiving Apollo requests from the same SvelteKit app just fine.

**Comment by AlecAivazis** [comment]
@thormuller I ran into something interseting while debugging this - if I change `/src/routes/qry/index.svelte` to look like 

```svelte
<script>
	import { query, graphql } from '$houdini';
	const { data } = query(graphql`
		query AllUsers {
			kitchenlab_users {
				email
				uid
			}
		}
	`);
</script>

{$data.kitchenlab_users.length}
```

Then I see the query being fired and a result is rendered. I'm going to keep poking at this to see if i can figure out the difference between this page the `Login` component but at least there is *some* progress.

**Comment by AlecAivazis** [comment]
Ah, I think i have found the problem. The [loading](https://kit.svelte.dev/docs#loading) documentation says that:

> load only applies to components that define pages, not the components that they import.

So I think this means that, at the moment, `query` only functions in pages and layouts (ie, things that are inside of `src/routes`). This is definitely not intended - `query` should absolutely work the way you expected. I'll try to get something out in the coming days to support this

**Comment by thormuller** [comment]
Aha, that makes sense. I can work around this in my situation. Again, many thanks for investigating my code–at least it seems like a useful case for future development. I'll stay tuned for how I can help this project as it blossoms!

**Comment by AlecAivazis** [comment]
No problem at all! I'm very excited to hear that at someone else is going to be using `houdini` - especially since you are clearly willing to opening tickets when you run into issues 😄 

I'm currently trying to gather some people I can reach out to in order to validate PRs coming out. Would you mind if I tag you when I add support for `query` outside of pages/and layouts to test?

**Comment by thormuller** [comment]
Absolutely! Happy to help.

**Comment by pixelmund** [comment]
Supporting queries outside pages is a must however svelte ssr in my understanding isn't async the only way to fetch is per load/preload i believe. What im curious about is what you will do for variables/function. Since there is no load in Components we will pass the variables directly to the query or what will/should it look like? Also this could be a good point to think about the api for variables. I don't know if i like the current approach.

**Comment by AlecAivazis** [comment]
@pixelmund - I agree that the current approach is kind of clunky. However, i'm not sure if there is an alternative. Definitely open to alternatives!

in order to get access to the page variables (so users can do something like pull a filter value from the url) the actual logic for computing the variable needs to be accessible in the module script where the actual network request happens. If the variables were just a static value, this wouldn't be a problem - the preprocessor could just copy the value up to the right script. Unfortunately that's too big of a limitation since a user could put all sorts of complicated in that function. That means that the preprocessor would be forced to hoist up any necessary logic to perform the computation. By forcing the user to define their variable function in the module context, we can guarantee that anything that the user used to compute their variables is also accessible to the `load` function without any complicated hoisting logic.

**Comment by pixelmund** [comment]
That makes completely sense to me. I can't think of another alternative, so explaining why it is like that would probably be the best decision right now.

**Comment by AlecAivazis** [comment]
@thormuller I _think_ I have a working update to support `query` in a component outside of `src/routes`. Mind pulling down #95 and giving it a shot?
